services:
  db:
    image: postgres:17.5
    container_name: go_clean_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_clean_api
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 123456789
      DB_NAME: school
      DB_PORT: 5432
      API_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    command: ['./go-clean-api']

volumes:
  postgresql_data:
